#!/bin/sh

APPDIR=$(dirname "$0")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/CUBE_IT_SCOTT_03.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-i586.jar:$APPDIR/lib/gluegen-rt-natives-linux-i586.jar:$APPDIR/lib/controlP5.jar:$APPDIR/lib/libTUIO.jar:$APPDIR/lib/TUIO.jar:$APPDIR/lib/jssc.jar:$APPDIR/lib/serial.jar" CUBE_IT_SCOTT_03 "$@"
